#!/bin/bash

sleep 1

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
purple='\033[0;35m'
cyan='\033[0;36m'
white='\033[0;37m'
rest='\033[0m'
plain='\033[0m'


check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo -e "${red}Error:${plain} Please run this script with root privileges."
        exit 1
    fi
}

finish() {
	echo -e " "
	echo -e " "
	echo -e " "
	echo -e " "
	echo -e "Now Finish Nameservers :\n "
	echo -e  "ns1.$domain \t $ip  \nns2.$domain \t $ip " |lolcat -as 100
 }
	 
ubuntu() {
	apt update  -y
	apt install bind9 bind9utils git bind9-doc lolcat figlet  -y 
	nameserver
}


