#!/bin/bash

# Author:   OuTiS

ORANGE=$(echo -ne '\e[38;5;214m')  
BLUE=$(echo -ne '\e[94m')           
RED=$(echo -ne '\e[31m')            
GREEN=$(echo -ne '\e[32m')          
ENDCOLOR=$(echo -ne '\e[0m')        
YELLOW=$(echo -ne '\033[0;33m')     
CYAN=$(echo -ne '\e[36m')           
MAGENTA=$(echo -ne '\e[35m')        
PURPLE=$(echo -ne '\e[38;5;129m') 

check_user_root(){
    if [ "$EUID" -ne 0 ]; then 
        echo -e ""
        echo -e "${RED}This script must be run as root. Please switch to the root user and try again.${ENDCOLOR}"
        exit 1
    fi
}

clear
check_user_root
sleep 1;

ZONE_DIR="/etc/coREDns/zones"
COREFILE="/etc/coREDns/Corefile"
COREDNS_SERVICE="coredns"
LOG_FILE="/var/log/coREDns_manager.log"

install_coREDns(){
    clear 
    sleep .5 
    echo -e "${BLUE}Checking operating system...${ENDCOLOR}"
    if [[ -f /etc/os-release ]]; then
        source /etc/os-release
        if [[ $ID != "ubuntu" ]]; then
            echo -e "${RED}This script only supports Ubuntu. Detected OS: $ID.${ENDCOLOR}"
            exit 1
        fi
    else
        echo -e "${RED}Cannot detect the operating system! Exiting.${ENDCOLOR}"
        exit 1
    fi

    echo -e "${BLUE}Installing CoreDNS on Ubuntu...${ENDCOLOR}"
    clear 
    sleep .5 
    apt update -y 2>/dev/null
    apt install -y curl  tar wget 2>/dev/null

    COREDNS_VERSION=$(curl -s https://github.com/coredns/coredns/releases | grep -oP '(?<=/coredns/coredns/releases/tag/v)[0-9]+\.[0-9]+\.[0-9]+' | head -1)

    if [[ -z "$COREDNS_VERSION" ]]; then
        echo -e "${RED}Failed to fetch the latest CoreDNS version.${ENDCOLOR}"
        exit 1
    fi

    echo -e "${BLUE}Latest CoreDNS version: ${COREDNS_VERSION}${ENDCOLOR}"
    echo -e "${BLUE}Downloading CoreDNS...${ENDCOLOR}"

    wget "https://github.com/coREDns/coREDns/releases/download/v${COREDNS_VERSION}/coREDns_${COREDNS_VERSION}_linux_amd64.tgz" -O /tmp/coredns.tgz

    if [[ $? -ne 0 ]]; then
        echo -e "${RED}Failed to download CoreDNS.${ENDCOLOR}"
        exit 1
    fi

    tar -xzf /tmp/coredns.tgz
    mv /tmp/coredns /usr/local/bin/
    DIR="/usr/local/bin/coredns"

if [ -d "$DIR" ]; then
    echo -e "${BLUE}Directory exists. Setting permissions.${ENDCOLOR}"
    chmod +x "$DIR"
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}Permissions set successfully.${ENDCOLOR}"
    else
        echo -e "${RED}Failed to set permissions.${ENDCOLOR}"
        exit 1
    fi
else
    echo -e "${RED}Directory does not exist. Creating directory.${ENDCOLOR}"
    mkdir -p "$DIR"
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}Directory created successfully.${ENDCOLOR}"
        chmod +x "$DIR"
        if [ $? -eq 0 ]; then
            echo -e "${GREEN}Permissions set successfully.${ENDCOLOR}"
        else
            echo -e "${RED}Failed to set permissions.${ENDCOLOR}"
            exit 1
        fi
    else
        echo -e "${RED}Failed to create directory.${ENDCOLOR}"
        exit 1
    fi
fi
rm -f /tmp/coredns.tgz
}

service_coREDns(){
    cat <<EOL > /etc/systemd/system/coredns.service
[Unit]
Description=CoreDNS DNS server
Documentation=https://coREDns.io
After=network.target

[Service]
ExecStart=/usr/local/bin/coredns -conf /etc/coREDns/Corefile
Restart=on-failure
User=root

[Install]
WantedBy=multi-user.target
EOL

    echo -e "${BLUE}Enabling and starting CoreDNS service...${ENDCOLOR}"
    systemctl daemon-reload
    systemctl enable coredns
    systemctl start coredns

    if systemctl is-active --quiet coredns; then
        echo -e "${GREEN}CoreDNS installed and running successfully.${ENDCOLOR}"
    else
        echo -e "${RED}CoreDNS installation failed or the service is not running.${ENDCOLOR}"
    fi
}

add_domain() {
    read -p "$(echo -e "${BLUE} Enter the domain name:  ${ENDCOLOR}")" domain
    read -p "$(echo -e "${BLUE} Enter the IP for the domain:  ${ENDCOLOR}")" ip 

    if ! [[ $domain =~ ^[a-zA-Z0-9.-]+$ ]]; then
        echo -e "${RED}Invalid domain name.${ENDCOLOR}"
        return
    fi

    if ! [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ || $ip =~ : ]]; then
        echo -e "${RED}Invalid IP address.${ENDCOLOR}"
        return
    fi

    zone_file="$ZONE_DIR/db.$domain"
    if [[ -f "$zone_file" ]]; then
        echo -e "${RED}Domain already exists.${ENDCOLOR}"
        return
    fi

    mkdir -p "$ZONE_DIR"
    cat <<EOL > "$zone_file"
\$TTL 3600
@       IN      SOA     ns1.$domain. admin.$domain. (
                        $(date +%Y%m%d%H)
                        3600
                        1800
                        604800
                        86400 )
@        IN      NS      ns1.$domain.
@        IN      NS      ns2.$domain.
ns1     IN      A       $ip
ns2     IN      A       $ip
@       IN      A       $ip
www     IN      A       $ip
EOL

    if [[ $ip =~ : ]]; then
        echo "ns1     IN    AAAA    $ip" >> "$zone_file"
        echo "ns2     IN    AAAA    $ip" >> "$zone_file"
    fi
    if [[ ! -f "$COREFILE" ]]; then
    echo -e "${YELLOW}Corefile not found. Creating a new one.${ENDCOLOR}"
    cat << EOF > "$COREFILE"
.:53 {
    log
    errors
    bind 0.0.0.0
    file "$ZONE_DIR/db.$domain"
}

zone "$domain" {
    file "$ZONE_DIR/db.$domain"
}
EOF
fi

    systemctl restart coredns
}

add_record() { 
  read -p "$(echo -e "${BLUE} Enter the domain name:  ${ENDCOLOR}")" domain
  zone_file="$ZONE_DIR/db.$domain" 
  
  if [[ ! -f "$zone_file" ]]; then
    echo -e "${RED}Domain does not exist.${ENDCOLOR}"
    return
  fi
  
  read -p "${BLUE}Enter the record type (A, CNAME, MX, ...): ${ENDCOLOR}" type
  read -p "${BLUE}Enter the record name: ${ENDCOLOR}" name
  read -p "${BLUE}Enter the record value: ${ENDCOLOR}" value

  if [[ "$type" == "MX" && ! "$value" =~ \.$ ]]; then
    value="$value."
  fi

  echo "$name    IN    $type    $value" >> "$zone_file"
  echo -e "${GREEN}Record added successfully.${ENDCOLOR}"
  echo "$(date) - Added record: $name $type $value to $domain" >> "$LOG_FILE"
}



remove_record() {
    read -p "${BLUE}Enter the domain name: ${ENDCOLOR}" domain 
    read -p "$(echo -e "${BLUE} Enter the domain name: ${ENDCOLOR}")" domain
    zone_file="$ZONE_DIR/db.$domain"

    if [[ ! -f "$zone_file" ]]; then
        echo -e "${RED}Domain does not exist.${ENDCOLOR}"
        return
    fi

    echo -e "${YELLOW}Current records:${ENDCOLOR}"
    cat "$zone_file"

    read -p "$(echo -e "${BLUE} Enter the record to remove (full line): ${ENDCOLOR}")" record
    sed -i "/$record/d" "$zone_file"
    echo -e "${GREEN}Record removed successfully.${ENDCOLOR}"
    echo "$(date) - Removed record: $record from $domain" >> "$LOG_FILE"
}

list_domains() {
    echo -e "${GREEN}Available domains:${ENDCOLOR}"
    domains=$(grep "zone" "$COREFILE" | awk '{print $2}' | tr -d '\";')

    if [[ -z "$domains" ]]; then
        echo -e "${RED}No domains found in CoreDNS configuration.${ENDCOLOR}"
        return
    fi

    echo -e "${GREEN}Please choose a domain from the list below:${ENDCOLOR}"
    echo "$domains"
    
    read -p "$(echo -e "${BLUE} Enter the domain name to get the name servers:  ${ENDCOLOR}")" domain
    if ! echo "$domains" | grep -w "$domain" &>/dev/null; then
        echo -e "${RED}Domain not found in the list.${ENDCOLOR}"
        return
    fi

    echo -e "${BLUE}For domain $domain, please set the following name servers in your domain management panel:${ENDCOLOR}"
    echo -e "ns1.$domain"
    echo -e "ns2.$domain"
    echo -e "${GREEN}Please make sure to set the above name servers in the DNS settings of your domain.${ENDCOLOR}"
}

reload_coREDns() {
    systemctl restart "$COREDNS_SERVICE"
    echo -e "${GREEN}CoreDNS reloaded successfully.${ENDCOLOR}"
    echo "$(date) - Reloaded CoreDNS" >> "$LOG_FILE"
}

backup_zones() {
    backup_file="/etc/coREDns/zones_backup_$(date +%Y%m%d%H%M%S).tar.gz"
    tar -czf "$backup_file" "$ZONE_DIR"
    echo -e "${GREEN}Backup created at $backup_file${ENDCOLOR}"
    echo "$(date) - Created backup: $backup_file" >> "$LOG_FILE"
}

restore_zones() {
    read -p "$(echo -e "${BLUE} Choose an option: ${ENDCOLOR}")" backup_file
    if [[ -f "$backup_file" ]]; then
        tar -xzf "$backup_file" -C /
        echo -e "${GREEN}Zones restoRED successfully.${ENDCOLOR}"
        echo "$(date) - RestoRED backup: $backup_file" >> "$LOG_FILE"
    else
        echo -e "${RED}Backup file not found.${ENDCOLOR}"
    fi
}

view_logs() {
    less "$LOG_FILE"
}

while true; do
    echo " "
    echo -e "${BLUE}╔═══════════════════════════════════════════════════════════╗${ENDCOLOR}"
    echo -e "                    ${GREEN} 🔥 NameShift 🔥   ${ENDCOLOR}"
    echo -e "                 ${CYAN} https://github.com/Niihil  ${ENDCOLOR}"
    echo -e "${BLUE}╚═══════════════════════════════════════════════════════════╝${ENDCOLOR}"
    echo " "

    echo -e "${RED}============================ ${ENDCOLOR}"
    echo -e "${RED}1.${ENDCOLOR}  Installing NameShift ${ENDCOLOR}"
    echo -e "${RED}2.${ENDCOLOR}  Add a new domain${ENDCOLOR}"
    echo -e "${RED}3.${ENDCOLOR}  Add a DNS record${ENDCOLOR}"
    echo -e "${RED}4.${ENDCOLOR}  Remove a DNS record${ENDCOLOR}"
    echo -e "${RED}5.${ENDCOLOR}  List all domains${ENDCOLOR}"
    echo -e "${RED}6.${ENDCOLOR}  Reload CoreDNS${ENDCOLOR}"
    echo -e "${RED}7.${ENDCOLOR}  Backup zones${ENDCOLOR}"
    echo -e "${RED}8.${ENDCOLOR}  Restore zones${ENDCOLOR}"
    echo -e "${RED}9.${ENDCOLOR}  View logs${ENDCOLOR}"
    echo -e "${RED}10.${ENDCOLOR} Exit${ENDCOLOR}"
    echo -e "${RED}============================ ${ENDCOLOR}"
    echo " "

    read -p "$(echo -e "${BLUE} Choose an option: ${ENDCOLOR}")" choice

    case $choice in
        1) install_coREDns ;;
        2) add_domain ; sleep 1 ;  service_coREDns;;
        3) add_record ;;
        4) remove_record ;;
        5) list_domains ;;
        6) reload_coREDns ;;
        7) backup_zones ;;
        8) restore_zones ;;
        9) view_logs ;;
        10) exit ;;
        *) echo -e "${RED}Invalid option. Please try again.${ENDCOLOR}" ;;
    esac

    read -p "$(echo -e "${BLUE}Press Enter to continue... ${ENDCOLOR}")" key
done

