#!/bin/bash

# Author:   OuTiS

ORANGE=$(echo -ne '\e[38;5;214m')
BLUE=$(echo -ne '\e[94m')
RED=$(echo -ne '\e[31m')
GREEN=$(echo -ne '\e[32m')
ENDCOLOR=$(echo -ne '\e[0m')
YELLOW=$(echo -ne '\033[0;33m') 
PURPLE=$(echo -ne '\e[35m')        

check_root()
{
	if [ "$EUID" -ne 0 ];then 
		echo -e "${RED}This script must be run as root. Please switch to the root user and try again.${ENDCOLOR}"
		exit 1
	fi
}

check_root

docker_service_check(){
    status="$(systemctl is-active docker )"
    if [ "${status}" = "active" ]; then
        echo -e "${GREEN}Service Docker Is Runing ... ${ENDCOLOR}"
    else
        echo -e "${RED} Service Docker Not Runing "
        exit 1
    fi
}

install_docker() {
    check_root
    local packages=(
        docker-ce
        docker-ce-cli
        containerd.io
        docker-buildx-plugin
        docker-compose-plugin
        python3-pip
    )

    echo -e "${YELLOW}Checking and installing Docker components...${ENDCOLOR}"

    for pkg in "${packages[@]}"; do
        echo -e "${YELLOW}Checking if $pkg is installed...${ENDCOLOR}"

        if ! dpkg -l | grep -qw "$pkg"; then
            echo -e "${YELLOW}$pkg not found. Installing...${ENDCOLOR}"
            if ! apt-get install -y "$pkg"; then
                echo -e "${RED}Failed to install $pkg. Exiting.${ENDCOLOR}"
                exit 1
            fi
            echo -e "${GREEN}$pkg installed successfully.${ENDCOLOR}"
        else
            echo -e "${GREEN}$pkg is already installed.${ENDCOLOR}"
        fi
    done

    echo -e "${GREEN}All Docker components are installed and ready.${ENDCOLOR}"
}

resolv_conf(){
echo  -e  "${GREEN}fix resolv.conf ${ENDCOLOR}"
while true; do echo "nameserver 8.8.8.8" > resolv.conf ; sleep 2s; done&
sleep 1
clear 
}

config_docker(){
while true; do echo "nameserver 8.8.8.8" > /etc/resolv.conf ; sleep 5; done&

if [ -d /etc/docker/daemon.json ]; then
    echo -e "File daemon.json Is Exits "
else 
    mkdir /etc/docker/daemon.json
fi
daemon=$(cat << EOL
{ "registry-mirrors": [ "https://focker.ir" ] }
EOL
)
echo "$daemon" > /etc/docker/daemon.json
}

check_run_docker(){

echo "${GREEN}Checking docker installation ${ENDCOLOR}"
if command -v docker &> /dev/null; then
    echo "${GREEN}Docker installation found${ENDCOLOR}\n"
else
    echo " ${RED}Docker installation not found. Please install docker. ${ENDCOLOR}\n"
        sleep 1
        echo " ${GREEN}Dokcer installing ... ${ENDCOLOR} \n\n"
        install_docker
fi

}

ZONES_DIR="$(pwd)/zones"
NAMED_CONF="$(pwd)/named.conf"
PDNS_CONF="$(pwd)/pdns.conf"

check_files() {
    if [ ! -d "$ZONES_DIR" ]; then
        echo -e "${RED}Directory zones not found: $ZONES_DIR${ENDCOLOR}"
        return 1
    fi

    if [ ! -f "$NAMED_CONF" ]; then
        echo -e "${RED}File named.conf not found: $NAMED_CONF${ENDCOLOR}"
        return 1
    fi

    if [ ! -f "$PDNS_CONF" ]; then
        echo -e "${RED}File pdns.conf not found: $PDNS_CONF${ENDCOLOR}"
        return 1
    fi

    return 0
}

docker_compose_init(){
pip install docker
pip install 'requests>=2.32.0'

}


create_docker_compose() {
    docker_compose_init
    cat <<EOF > docker-compose.yml

services:
  db:
    image: mysql:5.7
    container_name: pdns-admin-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql
      - ./schema.mysql.sql:/schema.mysql.sql
    networks:
      - pdns-network

  pdns:
    image: powerdns/pdns-auth-master
    container_name: pdns
    depends_on:
      - db
    environment:
      - gmysql-host=db
      - gmysql-user=pdns
      - gmysql-password=${PDNS_DB_PASSWORD}
      - gmysql-dbname=powerdns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8088:8088"
    volumes:
      - ./pdns.conf:/etc/powerdns/pdns.conf
    networks:
      - pdns-network

  pdns-admin:
    image: powerdnsadmin/pda-legacy:latest
    container_name: pdns-admin
    depends_on:
      - db
      - pdns
    environment:
      PDNS_API_URL: "http://pdns:8088"
      PDNS_API_KEY: ${PDNS_API_KEY}
      PDNS_ADMIN_USER: ${PDNS_ADMIN_USER}
      PDNS_ADMIN_PASSWORD: ${PDNS_ADMIN_PASSWORD}
      DB_HOST: "db:3306"
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "9191:80"
    volumes:
      - ./pdns-admin-config:/etc/pdns-admin
    networks:
      - pdns-network

networks:
  pdns-network:
    external: true

EOF

    echo -e "${GREEN}docker-compose.yml file created successfully.${ENDCOLOR}"
}

restart_docker_container_pdn(){
export $(cat .env | xargs)
docker-compose exec db bash -c "mysql -u root -p${MYSQL_ROOT_PASSWORD} powerdns < /schema.mysql.sql"
docker-compose  restart

}

start_docker_compose() {
    echo -e "${BLUE}Starting container with Docker Compose...${ENDCOLOR}"
    docker-compose up -d

    if [ $? -eq 0 ]; then
        echo -e "${GREEN}PowerDNS container started successfully.${ENDCOLOR}"
    else
        echo -e "${RED}Error starting PowerDNS container.${ENDCOLOR}"
        return 1
    fi
}

restart_docker_container() {
    CONTAINER_NAME="pdns"
    
    if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
        echo -e "${BLUE}Restarting the PowerDNS container...${ENDCOLOR}"
        
        docker restart $CONTAINER_NAME
        
        if [ $? -eq 0 ]; then
            echo -e "${GREEN}PowerDNS container restarted successfully.${ENDCOLOR}"
        else
            echo -e "${RED}Error restarting PowerDNS container.${ENDCOLOR}"
        fi
    else
        echo -e "${YELLOW}PowerDNS container is not running. Please start it first.${ENDCOLOR}"
    fi
}

resolv_conf
check_run_docker
config_docker
docker_service_check
config_docker


while true; do
    sleep 0.6 
    clear 
    echo " "
    echo -e "${BLUE}╔═══════════════════════════════════════════════════════════╗${ENDCOLOR}"
    echo -e "                    ${GREEN} 🔥 NameShift 🔥   ${ENDCOLOR}"
    echo -e "                 ${CYAN} https://github.com/Guilt92  ${ENDCOLOR}"
    echo -e "${BLUE}╚═══════════════════════════════════════════════════════════╝${ENDCOLOR}"
    echo " "
    echo -e "${RED}============================ ${ENDCOLOR}"
    echo -e "${RED}1.${ENDCOLOR}  Installing PowerDns ${ENDCOLOR}"
    echo -e "${RED}2.${ENDCOLOR}  Add a new domain${ENDCOLOR}"
    echo -e "${RED}3.${ENDCOLOR}  Multi Server${ENDCOLOR}"
    echo -e "${RED}4.${ENDCOLOR}  Add a DNS record${ENDCOLOR}"
    echo -e "${RED}5.${ENDCOLOR}  Remove a DNS record${ENDCOLOR}"
    echo -e "${RED}6.${ENDCOLOR}  List all domains${ENDCOLOR}"
    echo -e "${RED}7.${ENDCOLOR}  Reload PowerDns ${ENDCOLOR}"
    echo -e "${RED}8.${ENDCOLOR}  Backup zones${ENDCOLOR}"
    echo -e "${RED}9.${ENDCOLOR}  Restore zones${ENDCOLOR}"
    echo -e "${RED}10.${ENDCOLOR} Check Format Db Domains ${ENDCOLOR}"
    echo -e "${RED}11.${ENDCOLOR} Exit${ENDCOLOR}"
    echo -e "${RED}============================ ${ENDCOLOR}"
    echo " "

    read -p "$(echo -e "${BLUE} Choose an option: ${ENDCOLOR}")" choice

    case $choice in
        1) install_pdn ; sleep 1; reload_pdns ;;
        2) add_domain ; sleep 1 ;  service_pdns;;
        3) multi ; sleep 2 ;  exit;;
        4) add_record ;;
        5) remove_record ;;
        6) list_domains ;;
        7) reload_pdns ;;
        8) backup_zones ;;
        9) restore_zones ;;
        10) valid_file_db;;
        11) exit ;;
        *) echo -e "${RED}Invalid option. Please try again.${ENDCOLOR}" ; sleep 1.5 ;;
    esac

    read -p "$(echo -e "${BLUE}Press Enter to continue... ${ENDCOLOR}")" key
done





