#!/bin/bash

# Author:   OuTiS

set -a
source .env
set +a

ORANGE=$(echo -ne '\e[38;5;214m')
BLUE=$(echo -ne '\e[94m')
RED=$(echo -ne '\e[31m')
GREEN=$(echo -ne '\e[32m')
ENDCOLOR=$(echo -ne '\e[0m')
YELLOW=$(echo -ne '\033[0;33m') 
PURPLE=$(echo -ne '\e[35m')        
CYAN=$(echo -ne '\e[36m')


check_root()
{
	if [ "$EUID" -ne 0 ];then 
		echo -e "${RED}This script must be run as root. Please switch to the root user and try again.${ENDCOLOR}"
		exit 1
	fi
}

check_root

docker_service_check(){
    status="$(systemctl is-active docker )"
    if [ "${status}" = "active" ]; then
        echo -e "${GREEN}Service Docker Is Runing ... ${ENDCOLOR}"
    else
        echo -e "${RED} Service Docker Not Runing "
        sleep 1
        systemctl unmask docker
        systemctl restart docker 
        echo -e "${RED} Service Docker Is Runing "
    fi
}

install_docker() {
    check_root
    local packages=(
         docker.io
         docker-doc
         docker-compose
         docker-compose-v2
         podman-docker
         containerd
         runc
         python3-pip
    )

    echo -e "${YELLOW}Checking and installing Docker components...${ENDCOLOR}"

    for pkg in "${packages[@]}"; do
        echo -e "${YELLOW}Checking if $pkg is installed...${ENDCOLOR}"

        if ! dpkg -l | grep -qw "$pkg"; then
            echo -e "${YELLOW}$pkg not found. Installing...${ENDCOLOR}"
            if ! apt-get install -y "$pkg"; then
                echo -e "${RED}Failed to install $pkg. Exiting.${ENDCOLOR}"
                exit 1
            fi
            echo -e "${GREEN}$pkg installed successfully.${ENDCOLOR}"
        else
            echo -e "${GREEN}$pkg is already installed.${ENDCOLOR}"
        fi
    done

    echo -e "${GREEN}All Docker components are installed and ready.${ENDCOLOR}"
}

resolv_conf() {
  echo -e "${GREEN}fix resolv.conf ${ENDCOLOR}"
  ( while true; do echo "nameserver 8.8.8.8" > resolv.conf; sleep 2s; done > /dev/null 2>&1 ) &
  disown
  sleep 1
  clear
}

config_docker(){

if [ -d /etc/docker/daemon.json ]; then
    echo -e "File daemon.json Is Exits "
else 
    mkdir /etc/docker/daemon.json
fi
daemon=$(cat << EOL
{ "registry-mirrors": [ "https://focker.ir" ] }
EOL
)
echo "$daemon" > /etc/docker/daemon.json
}

check_run_docker(){
  echo -e "${GREEN}Checking docker installation ${ENDCOLOR}"
  if command -v docker &> /dev/null; then
      echo -e "${GREEN}Docker installation found${ENDCOLOR}\n"
  else
      echo -e "${RED}Docker installation not found. Please install docker. ${ENDCOLOR}\n"
      sleep 1
      echo -e "${GREEN}Docker installing ... ${ENDCOLOR}\n\n"
      install_docker
  fi
}

PDNS_CONF="./pdns.conf"

check_files() {

    if [ ! -f "$PDNS_CONF" ]; then
        echo -e "${RED}File pdns.conf not found: $PDNS_CONF${ENDCOLOR}"
        return 1
    fi

    return 0
}

docker_compose_init(){
install_docker 
pip install docker
pip install 'requests>=2.32.0'

}

create_docker_compose() {
    docker_compose_init
    cat <<EOF > docker-compose.yml

services:
  db:
    image: mysql:5.7
    container_name: pdns-admin-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql
      - ./schema.mysql.sql:/schema.mysql.sql
    networks:
      - pdns-network

  pdns:
    image: powerdns/pdns-auth-master
    container_name: pdns
    depends_on:
      - db
    environment:
      - gmysql-host=db
      - gmysql-user=pdns
      - gmysql-password=${PDNS_DB_PASSWORD}
      - gmysql-dbname=powerdns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8088:8088"
    volumes:
      - ./pdns.conf:/etc/powerdns/pdns.conf
    networks:
      - pdns-network

  pdns-admin:
    image: powerdnsadmin/pda-legacy:latest
    container_name: pdns-admin
    depends_on:
      - db
      - pdns
    environment:
      PDNS_API_URL: "http://pdns:8088"
      PDNS_API_KEY: ${PDNS_API_KEY}
      PDNS_ADMIN_USER: ${PDNS_ADMIN_USER}
      PDNS_ADMIN_PASSWORD: ${PDNS_ADMIN_PASSWORD}
      DB_HOST: "db:3306"
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "9191:80"
    volumes:
      - ./pdns-admin-config:/etc/pdns-admin
    networks:
      - pdns-network

networks:
  pdns-network:
    external: true

EOF

    echo -e "${GREEN}docker-compose.yml file created successfully.${ENDCOLOR}"
}

start_docker_compose() {
    clear
    echo -e "${YELLOW}Starting Docker Compose...${ENDCOLOR}"
    if docker-compose up -d; then
        echo -e "${GREEN} All containers started successfully.${ENDCOLOR}"
    else
        echo -e "${RED}Failed to start containers!${ENDCOLOR}"
        exit 1
    fi
}

restart_docker_container_pdn() {
    export $(grep -Ev '^\s*#' .env | xargs)

    docker-compose exec -T db mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "
        CREATE DATABASE IF NOT EXISTS powerdns;
        CREATE USER IF NOT EXISTS 'pdns'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
        GRANT ALL PRIVILEGES ON powerdns.* TO 'pdns'@'%';
        FLUSH PRIVILEGES;
    "

    docker-compose exec -T db mysql -u root -p"$MYSQL_ROOT_PASSWORD" powerdns < /schema.mysql.sql

    docker-compose restart pdns

    echo -e "${GREEN}✅ Database initialized and PowerDNS container restarted successfully.${ENDCOLOR}"
}



view_logs() {
    sleep 0.5
    clear 
    echo -e "${BLUE}==================== ${GREEN}PowerDNS Logs Viewer ${BLUE}====================${ENDCOLOR}"
    echo -e "${CYAN}Which container logs do you want to view? (Enter the number):${ENDCOLOR}"
    echo -e "1. ${YELLOW}pdns${ENDCOLOR} - PowerDNS container logs"
    echo -e "2. ${PURPLE}pdns-admin${ENDCOLOR} - PowerDNS Admin container logs"
    echo -e "3. ${RED}Exit${ENDCOLOR} - Exit logs viewer and return to menu"
    
    read -p "Enter your choice (1/2/3): " choice
    case $choice in
        1)
            container="pdns"
            ;;
        2)
            container="pdns-admin"
            ;;
        3)
            echo -e "${CYAN}Exiting...${ENDCOLOR}"
            return
            ;;
        *)
            echo -e "${RED}Invalid choice, please try again.${ENDCOLOR}"
            return
            ;;
    esac

    trap 'echo -e "${CYAN}Returning to the main menu...${ENDCOLOR}"; return' SIGINT

    clear
    echo -e "${BLUE}==================== ${GREEN}PowerDNS Logs Viewer ${BLUE}====================${ENDCOLOR}"
    echo -e "${CYAN}Displaying live logs for $container container (last 10 lines)...${ENDCOLOR}"
    echo -e "${CYAN}Press ${RED}Ctrl+C ${CYAN} to exit logs view and return to the menu.${ENDCOLOR}"

    while true; do
        clear
        docker logs --tail 10 -f $container | while IFS= read -r line; do
            if [[ "$container" == "pdns" ]]; then
                echo -e "${YELLOW}[pdns] ${line}${ENDCOLOR}"
            else
                echo -e "${PURPLE}[pdns-admin] ${line}${ENDCOLOR}"
            fi
        done
    done
}

restart_container() {
    echo -e "${BLUE}==================== ${GREEN}PowerDNS Container Restarter ${BLUE}====================${ENDCOLOR}"
    echo -e "${CYAN}Which container do you want to restart? (Enter the number):${ENDCOLOR}"
    echo -e "1. ${YELLOW}pdns${ENDCOLOR} - PowerDNS container"
    echo -e "2. ${PURPLE}pdns-admin${ENDCOLOR} - PowerDNS Admin container"
    echo -e "3. ${CYAN}pdns-admin-db${ENDCOLOR} - PowerDNS Database container"
    echo -e "4. ${RED}Exit${ENDCOLOR} - Cancel and return to menu"

    read -p "Enter your choice (1/2/3/4): " choice
    case $choice in
        1)
            CONTAINER_NAME="pdns"
            ;;
        2)
            CONTAINER_NAME="pdns-admin"
            ;;
        3)
            CONTAINER_NAME="pdns-admin-db"
            ;;
        4)
            echo -e "${CYAN}Exiting restart menu...${ENDCOLOR}"
            return
            ;;
        *)
            echo -e "${RED}Invalid choice, please try again.${ENDCOLOR}"
            return
            ;;
    esac

    if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
        echo -e "${BLUE}Restarting container $CONTAINER_NAME...${ENDCOLOR}"
        docker restart $CONTAINER_NAME
        if [ $? -eq 0 ]; then
            echo -e "${GREEN}Container $CONTAINER_NAME restarted successfully.${ENDCOLOR}"
        else
            echo -e "${RED}Error restarting container $CONTAINER_NAME.${ENDCOLOR}"
        fi
    else
        echo -e "${YELLOW}Container $CONTAINER_NAME is not running. Please start it first.${ENDCOLOR}"
    fi
}

config_init_docker(){
resolv_conf
check_run_docker
config_docker
docker_service_check

}

install_pdns(){
config_init_docker
check_files
docker_compose_init
create_docker_compose
start_docker_compose
restart_docker_container_pdn

}


while true; do
    sleep 0.6 
    clear 
    echo " "
    echo -e "${BLUE}╔═══════════════════════════════════════════════════════════╗${ENDCOLOR}"
    echo -e "                    ${GREEN} 🔥 NameShift 🔥   ${ENDCOLOR}"
    echo -e "                 ${CYAN} https://github.com/Guilt92  ${ENDCOLOR}"
    echo -e "${BLUE}╚═══════════════════════════════════════════════════════════╝${ENDCOLOR}"
    echo " "
    echo -e "${RED}============================ ${ENDCOLOR}"
    echo -e "${RED}1.${ENDCOLOR} Installing PowerDns ${ENDCOLOR}"
    echo -e "${RED}2.${ENDCOLOR} Reload PowerDns ${ENDCOLOR}"
    echo -e "${RED}3.${ENDCOLOR} View Logs${ENDCOLOR}"
    echo -e "${RED}4.${ENDCOLOR} Exit ${ENDCOLOR}" 
    echo -e "${RED}============================ ${ENDCOLOR}"
    echo " "

    read -p "$(echo -e "${BLUE} Choose an option: ${ENDCOLOR}")" choice

    case $choice in
        1) install_pdns ;;
        2) restart_container ;;
        3) view_logs ;;
        4) exit ;;
        *) echo -e "${RED}Invalid option. Please try again.${ENDCOLOR}" ; sleep 1.5 ;;
    esac

    read -p "$(echo -e "${BLUE}Press Enter to continue... ${ENDCOLOR}")" key
done





