#!/bin/bash


# Author:   OuTiS

ORANGE=$(echo -ne '\e[38;5;214m')
BLUE=$(echo -ne '\e[94m')
RED=$(echo -ne '\e[31m')
GREEN=$(echo -ne '\e[32m')
ENDCOLOR=$(echo -ne '\e[0m')
YELLOW=$(echo -ne '\033[0;33m') 
PURPLE=$(echo -ne '\e[35m')        


check_root()
{
	if [ "$EUID" -ne 0 ];then 
		echo -e "${RED}This script must be run as root. Please switch to the root user and try again.${ENDCOLOR}"
		exit 1
	fi
}


docker_service_check(){
    status="$(systemctl is-active docker )"
    if [ "${status}" = "active" ]; then
        echo -e "${GREEN}Service Docker Is Runing ... ${ENDCOLOR}"
    else
        echo -e "${RED} Service Docker Not Runing "
        exit 1
    fi
}


install_docker() {
    check_root
    local packages=(
        docker-ce
        docker-ce-cli
        containerd.io
        docker-buildx-plugin
        docker-compose-plugin
    )

    echo -e "${YELLOW}Checking and installing Docker components...${ENDCOLOR}"

    for pkg in "${packages[@]}"; do
        echo -e "${YELLOW}Checking if $pkg is installed...${ENDCOLOR}"

        if ! dpkg -l | grep -qw "$pkg"; then
            echo -e "${YELLOW}$pkg not found. Installing...${ENDCOLOR}"
            if ! apt-get install -y "$pkg"; then
                echo -e "${RED}Failed to install $pkg. Exiting.${ENDCOLOR}"
                exit 1
            fi
            echo -e "${GREEN}$pkg installed successfully.${ENDCOLOR}"
        else
            echo -e "${GREEN}$pkg is already installed.${ENDCOLOR}"
        fi
    done

    echo -e "${GREEN}All Docker components are installed and ready.${ENDCOLOR}"
}



resolv_conf(){
echo  -e  "${GREEN}fix resolv.conf ${ENDCOLOR}"
while true; do echo "nameserver 8.8.8.8" > resolv.conf ; sleep 2s; done&
sleep 1
clear 
}


config_docker(){
while true; do echo "nameserver 8.8.8.8" > /etc/resolv.conf ; sleep 5; done&

if [ -d /etc/docker/daemon.json ]; then
    echo -e "File daemon.json Is Exits "
else 
    mkdir /etc/docker/daemon.json
fi
daemon=$(cat << EOL
{ "registry-mirrors": [ "https://focker.ir" ] }
EOL
)
echo "$daemon" > /etc/docker/daemon.json
}



check_run_docker(){

echo "${GREEN}Checking docker installation ${ENDCOLOR}"
if command -v docker &> /dev/null; then
    echo "${GREEN}Docker installation found${ENDCOLOR}\n"
else
    echo " ${RED}Docker installation not found. Please install docker. ${ENDCOLOR}\n"
        sleep 1
        echo " ${GREEN}Dokcer installing ... ${ENDCOLOR} \n\n"
        install_docker
fi

}

